### ISSUE TITLE
Interconnect inspector throwing an NPE if unable to read data via AMQP management

### ISSUE THREAD

**Issue by orpiske** [maestro-performance/maestro-java#113]
The code should check whether the message object was received correctly.

> ERROR 05:16:19,267 org.maestro.inspector.base.InspectorContainer - Error running the inspector: null
> java.lang.NullPointerException
>         at org.maestro.inspector.amqp.InterconnectReadData.collectRouterLinkInfo(InterconnectReadData.java:104)
>         at org.maestro.inspector.amqp.InterconnectInspector.start(InterconnectInspector.java:174)
>         at org.maestro.inspector.base.InspectorContainer.run(InspectorContainer.java:34)
>         at java.lang.Thread.run(Thread.java:748)

**Comment by orpiske** [comment]
Fixed.
