### ISSUE TITLE
DrainObserver#onStop does not respect drainDeadline

### ISSUE THREAD

**Issue by k-wall** [maestro-performance/maestro-java#138]
I am using `maestroperf/maestro-worker:1.5.2`.  When a worker in the JMSReceiverWorker role completes, the worker is not draining the queue correctly.  The draining finsihes prematurely and does not respect the  `worker.observer.deadline.secs confguration` setting.

Looking at the code, I see that `org.maestro.worker.common.watchdog.DrainObserver#onStop` invokes `org.maestro.worker.common.WorkerContainer#waitForComplete`, which in turn calls `org.maestro.worker.common.WorkerContainer#stop(long)`.  The calls stop on all the workers without giving them the `drainDeadline` timeout to do their work.

**Comment by k-wall** [comment]
Fixing this problem exposes another.  I am now sometimes seeing the client fail.  I think what is happening is the worker (JMS receiver) is unable to respond to the unassign because it is busy draining the queue.  Perhaps making org.maestro.client.Maestro#set(java.util.function.Function<T,java.util.concurrent.CompletableFuture<java.util.List<? extends org.maestro.common.client.notes.MaestroNote>>>, T) tunable would help, but dislike having too many knobs to twiddle.

```
10:35:39,924 org.maestro.tests.cluster.AbstractStrategy.unassign:64 [ERROR] Not enough replies trying to unassign node worker@maestro-worker-866f995568-548fd as sender Not enough replies when trying to execute a command on the test cluster
org.maestro.common.client.exceptions.NotEnoughRepliesException: Not enough replies when trying to execute a command on the test cluster
        at org.maestro.client.Maestro.set(Maestro.java:642)
        at org.maestro.client.Maestro.set(Maestro.java:654)
        at org.maestro.client.Maestro.exec(Maestro.java:731)
        at org.maestro.tests.cluster.AbstractStrategy.unassign(AbstractStrategy.java:60)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
        at org.maestro.tests.cluster.AbstractStrategy.reset(AbstractStrategy.java:100)
        at org.maestro.tests.rate.AbstractFixedRateExecutor.stopServices(AbstractFixedRateExecutor.java:164)
        at org.maestro.tests.rate.AbstractFixedRateExecutor.runTest(AbstractFixedRateExecutor.java:109)
        at org.maestro.tests.rate.StraightFixedRateTestExecutor.run(StraightFixedRateTestExecutor.java:68)
        at org.maestro.tests.TestExecutor$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at singlepoint.FixedRateTest.run(FixedRateTest.groovy:145)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
        at groovy.lang.GroovyShell.run(GroovyShell.java:228)
        at org.maestro.cli.main.actions.exec.GroovyWrapper.run(GroovyWrapper.java:29)
        at org.maestro.cli.main.actions.ExecAction.run(ExecAction.java:69)
        at org.maestro.cli.main.MaestroCliMain.main(MaestroCliMain.java:98)
```

**Comment by orpiske** [comment]
I think I am seeing the same problem when running the integration tests. 

I don't really know the best approach yet but I am investigating if I can make the worker return a try again error when receiving a request while the drain is running.

**Comment by k-wall** [comment]
In my case, I had a misconfigation.  I had configured `worker.observer.deadline.secs` to a value larger then `client.drain.deadline.secs` so the client was timing out the drain (which it just swallows with a WARN) and then going on to fail as the unassign failed.
