### ISSUE TITLE
Test fails if JMS sender is blocked (sending link awaiting credit) when test completes

### ISSUE THREAD

**Issue by k-wall** [maestro-performance/maestro-java#141]
If the JMS sender worker is blocked from sending when the test is due to finish, the test will report failure.  The tests using the Qpid JMS Client, this corresponds to the condition where the sending link is blocked awaiting credit.  When the peer is the Artemis Broker, this can correspond to a queue/disk full situation (or even https://issues.apache.org/jira/browse/ARTEMIS-1898).

```
12:13:34,709 ERROR [worker-1] org.maestro.worker.jms.JMSSenderWorker - Unexpected error while running the sender worker: java.lang.InterruptedException
javax.jms.JMSException: java.lang.InterruptedException
        at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
        at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
        at org.apache.qpid.jms.JmsConnection.send(JmsConnection.java:776)
        at org.apache.qpid.jms.JmsNoTxTransactionContext.send(JmsNoTxTransactionContext.java:37)
        at org.apache.qpid.jms.JmsSession.send(JmsSession.java:910)
        at org.apache.qpid.jms.JmsSession.send(JmsSession.java:791)
        at org.apache.qpid.jms.JmsMessageProducer.sendMessage(JmsMessageProducer.java:247)
        at org.apache.qpid.jms.JmsMessageProducer.send(JmsMessageProducer.java:177)
        at org.apache.qpid.jms.JmsMessageProducer.send(JmsMessageProducer.java:166)
        at org.maestro.worker.jms.JMSSenderClient.sendMessages(JMSSenderClient.java:107)
        at org.maestro.worker.jms.JMSSenderWorker.runLoadLoop(JMSSenderWorker.java:202)
        at org.maestro.worker.jms.JMSSenderWorker.start(JMSSenderWorker.java:146)
        at org.maestro.worker.jms.JMSSenderWorker.run(JMSSenderWorker.java:269)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.maestro.worker.jms.JMSSenderWorker.run(JMSSenderWorker.java:269)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.lang.InterruptedException
        at org.apache.qpid.jms.util.IOExceptionSupport.create(IOExceptionSupport.java:45)
        at org.apache.qpid.jms.provider.ConservativeProviderFuture.sync(ConservativeProviderFuture.java:125)
        at org.apache.qpid.jms.JmsConnection.send(JmsConnection.java:771)
        ... 15 more
Caused by: java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.apache.qpid.jms.provider.ConservativeProviderFuture.sync(ConservativeProviderFuture.java:117)
        ... 16 more

```

**Comment by k-wall** [comment]
I think the test worker should be change not to consider this condition fatal.

**Comment by orpiske** [comment]
I am thinking how to handle this without losing the ability to find real issues during the client shutdown. 

I wonder if I should do something like this, when the protocol is AMQP 1.0: catch JMSException and If the cause is `java.lang.InterruptedException`, then log a warning and set the status to WORKER_EXIT_SUCCESS.
