### ISSUE TITLE
Fix: support for large test cases which take a long time to finish when having too many concurrent workers/connections

### ISSUE THREAD

**Issue by orpiske** [maestro-performance/maestro-java#25]
This error is not, necessarily, on Maestro, however it needs to handle situations like this much better.

 ```ERROR 03:42:06,102  net.orpiske.mpt.maestro.worker.jms.JMSReceiverWorker - Unable to start the receiver worker: Remote did not respond to a drain request in time
org.apache.qpid.jms.JmsOperationTimedOutException: Remote did not respond to a drain request in time
	at org.apache.qpid.jms.provider.amqp.AmqpConsumer$1.run(AmqpConsumer.java:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) ```

**Comment by orpiske** [comment]
This **may** be a problem on some client libraries but it needs further investigation.

**Comment by orpiske** [comment]
This is caused due to an issue on Qpid Dispatch. Closing it.
