### ISSUE TITLE
Abnormal disconnects disrupting the communication between the peers

### ISSUE THREAD

**Issue by orpiske** [maestro-performance/maestro-java#81]
On the client:

> 09:36:08 Jul 04, 2018 9:36:04 AM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
> 09:36:08 SEVERE: maestro-java-099cb7d6-2226-432f-aa1e-a0a587ee2e86: Timed out as no activity, keepAlive=60,000 lastOutboundActivity=1,530,689,704,614 lastInboundActivity=1,530,689,687,739 time=1,530,689,764,614 lastPing=1,530,689,704,614
> 09:36:08 [WARN] Connection lost
> 09:36:08 [ERROR] Disconnected from the broker: reconnecting
> 09:36:08 [INFO] Connecting to Maestro Broker
> 09:36:08 [ERROR] Unhandled exception: Unable to publish message: MqttException
> 09:36:08 org.maestro.common.exceptions.MaestroConnectionException: Unable to publish message: MqttException
> 09:36:08 	at org.maestro.client.exchange.MaestroMqttClient.publish(MaestroMqttClient.java:127)
> 09:36:08 	at org.maestro.client.exchange.MaestroMqttClient.publish(MaestroMqttClient.java:183)
> 09:36:08 	at org.maestro.client.Maestro.logRequest(Maestro.java:509)
> 09:36:08 	at org.maestro.reports.downloaders.BrokerDownloader.download(BrokerDownloader.java:178)
> 09:36:08 	at org.maestro.reports.downloaders.BrokerDownloader.downloadLastSuccessful(BrokerDownloader.java:183)
> 09:36:08 	at org.maestro.tests.AbstractTestProcessor.doProcess(AbstractTestProcessor.java:121)
> 09:36:08 	at org.maestro.tests.AbstractTestProcessor.processNotifySuccess(AbstractTestProcessor.java:136)
> 09:36:08 	at org.maestro.tests.rate.FixedRateTestExecutor$TestNotificationCallBack.call(FixedRateTestExecutor.java:136)
> 09:36:08 	at org.maestro.client.exchange.MaestroCollector.noteArrived(MaestroCollector.java:45)
> 09:36:08 	at org.maestro.client.exchange.AbstractMaestroPeer.messageArrived(AbstractMaestroPeer.java:177)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
> 09:36:08 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 09:36:08 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09:36:08 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 09:36:08 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 09:36:08 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 09:36:08 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 09:36:08 	at java.lang.Thread.run(Thread.java:748)
> 09:36:08 Caused by: MqttException (0) - java.lang.InterruptedException
> 09:36:08 	at org.eclipse.paho.client.mqttv3.internal.Token.waitForResponse(Token.java:148)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:108)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.MqttClient.publish(MqttClient.java:583)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.MqttClient.publish(MqttClient.java:575)
> 09:36:08 	at org.maestro.client.exchange.MaestroMqttClient.publish(MaestroMqttClient.java:124)
> 09:36:08 	... 19 more
> 09:36:08 Caused by: java.lang.InterruptedException
> 09:36:08 	at java.lang.Object.wait(Native Method)
> 09:36:08 	at java.lang.Object.wait(Object.java:502)
> 09:36:08 	at org.eclipse.paho.client.mqttv3.internal.Token.waitForResponse(Token.java:143)
> 09:36:08 	... 24 more

On Maestro broker:

> 2018-07-04 09:36:04,640 | WARN  | Failed to send frame MQTTFrame { type: PINGRESP, qos: AT_MOST_ONCE, dup:false } | org.apache.activemq.transport.mqtt.MQTTProtocolConverter | ActiveMQ Transport: tcp:///10.37.144.188:56536@1883
> java.net.SocketException: Broken pipe (Write failed)
>         at java.net.SocketOutputStream.socketWrite0(Native Method)[:1.8.0_171]
>         at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)[:1.8.0_171]
>         at java.net.SocketOutputStream.write(SocketOutputStream.java:155)[:1.8.0_171]
>         at org.apache.activemq.transport.tcp.TcpBufferedOutputStream.flush(TcpBufferedOutputStream.java:115)[activemq-client-5.11.3.jar:5.11.3]
>         at java.io.DataOutputStream.flush(DataOutputStream.java:123)[:1.8.0_171]
>         at org.apache.activemq.transport.tcp.TcpTransport.oneway(TcpTransport.java:176)[activemq-client-5.11.3.jar:5.11.3]
>         at org.apache.activemq.transport.mqtt.MQTTTransportFilter.sendToMQTT(MQTTTransportFilter.java:120)[activemq-mqtt-5.11.3.jar:5.11.3]
>         at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.sendToMQTT(MQTTProtocolConverter.java:178)[activemq-mqtt-5.11.3.jar:5.11.3]
>         at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:191)[activemq-mqtt-5.11.3.jar:5.11.3]
>         at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)[activemq-mqtt-5.11.3.jar:5.11.3]
>         at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)[activemq-client-5.11.3.jar:5.11.3]
>         at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:214)[activemq-client-5.11.3.jar:5.11.3]
>         at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:196)[activemq-client-5.11.3.jar:5.11.3]
>         at java.lang.Thread.run(Thread.java:748)[:1.8.0_171]
>

**Comment by orpiske** [comment]
Some possible causes for this (as I have found so far):
- Poor network reliability
- Maestro broker running out of JVM heap (or, at least, suffering from long GC pauses)

**Comment by orpiske** [comment]
Fixed with #0b0f3bda + #93606.
