### ISSUE TITLE
NPE reported to the logs if receiver failed.

### ISSUE THREAD

**Issue by k-wall** [maestro-performance/maestro-java#83]
The error handling in the maestro-client (1.3.2) could use a little improvement.   In the failure case below a maestro receiver had failed, but the client went on to NPE and report a stack trace. The log from the client looked like this:

```
Using Running exec
Connecting to mqtt://broker
[INFO] Connecting to Maestro Broker
[WARN] Connection to tcp://broker:1883 completed (reconnect = false)
[INFO] No management interface address was given
[INFO] Starting the warm up execution
[INFO] Known peers recorded: 2
[INFO] Registering data server at http://10.129.10.17:8000
[INFO] Registering data server at http://10.131.10.14:8000
[INFO] Applying test warm-up profile
[INFO] Setting endpoint URL to amqp://messaging.maestro-standard.svc:5672/queue?durable=true
[INFO] Setting warm-up rate to 0
[INFO] Setting warm-up duration to 10000
[INFO] Setting warm-up parallel count to 1
[INFO] Setting fail-condition-latency to 0
[INFO] Setting message size to 512
[INFO] Estimated time for warm-up completion: 630 secs
[INFO] Test failed on receiver@10.129.10.17 after 0 executions: Timed out while waiting to connect
[INFO] Test parameter used: FixedRateTestProfile{rate=0, parallelCount=1, maximumLatency=0, duration=0d0h1m0s, messageSize='512'} AbstractTestProfile{testExecutionNumber=0}
[INFO] Waiting for 3 seconds for the backend to flush their data
[INFO] Downloading the receiver report file http://10.129.10.17:8000/logs/tests/lastSuccessful/receiverd-rate.csv.gz
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[INFO] Downloading the receiver report file http://10.129.10.17:8000/logs/tests/lastSuccessful/test.properties
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
Jul 05, 2018 6:29:55 PM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: maestro-java-185e98f2-16a7-4b8d-8443-0622b28c408a: Timed out as no activity, keepAlive=60,000 lastOutboundActivity=1,530,815,335,661 lastInboundActivity=1,530,815,302,739 time=1,530,815,395,661 lastPing=1,530,815,335,661
[WARN] Connection lost
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.maestro.reports.downloaders.DefaultDownloader.downloadReport(DefaultDownloader.java:78)
	at org.maestro.reports.downloaders.DefaultDownloader.downloadLastSuccessful(DefaultDownloader.java:101)
	at org.maestro.tests.AbstractTestProcessor.doProcess(AbstractTestProcessor.java:121)
	at org.maestro.tests.AbstractTestProcessor.processNotifyFail(AbstractTestProcessor.java:154)
	at org.maestro.tests.rate.FixedRateTestExecutor$TestNotificationCallBack.call(FixedRateTestExecutor.java:141)
	at org.maestro.client.exchange.MaestroCollector.noteArrived(MaestroCollector.java:45)
	at org.maestro.client.exchange.AbstractMaestroPeer.messageArrived(AbstractMaestroPeer.java:177)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[ERROR] Disconnected from the broker: reconnecting
[INFO] Connecting to Maestro Broker
[WARN] Connection to tcp://broker:1883 completed (reconnect = false)
Exception in thread "Thread-3" java.lang.NullPointerException
	at org.maestro.client.exchange.AbstractMaestroPeer.subscribe(AbstractMaestroPeer.java:153)
	at org.maestro.client.exchange.AbstractMaestroPeer.reconnect(AbstractMaestroPeer.java:124)
	at org.maestro.client.exchange.AbstractMaestroExecutor.run(AbstractMaestroExecutor.java:80)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Downloading the receiver report file http://10.129.10.17:8000/logs/tests/lastSuccessful/receiverd-latency.hdr
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[WARN] Remote resource not found or not available yet. Retrying in 5 seconds
[INFO] Not enough notifications received yet: received 1 of 2
[INFO] Backends might be quiescing after the test execution
[INFO] Not enough notifications received yet: received 1 of 2
[INFO] Backends might be quiescing after the test execution
[INFO] Not enough notifications received yet: received 1 of 2
[INFO] Backends might be quiescing after the test execution
[INFO] Test warm-up completed unsuccessfully
[ERROR] Warm up execution failed

```

**Comment by k-wall** [comment]
I'm seeing this problem every now and then but have not got to the bottom of it.  My working theory is that the download is either slow or stuck.  This blocks the MQTT worker thread (the call to #messageArrived is synchronous).  The delay exceeds the MQTT keep alive timeout so keep alive logic tries to recreate the connection resulting in the InterruptedException and subsequently a NPE.

**Comment by orpiske** [comment]
@k-wall thanks for the details. I have been trying to reproduce this one, but I wasn't able to do that yet. This seems related to #81 (which received a suggested fix and I'm QE'ing it) but I am not sure yet.

**Comment by orpiske** [comment]
Ok, I managed to reproduce it: it's caused during the re-connection. When running through the client API interface (org.maestro.client.Maestro) the code self-initializes the connection and subscription (ref: https://github.com/maestro-performance/maestro-java/blob/master/maestro-client/src/main/java/org/maestro/client/exchange/MaestroCollectorExecutor.java#L44) instead of calling the start method from the parent class (https://github.com/maestro-performance/maestro-java/blob/master/maestro-client/src/main/java/org/maestro/client/exchange/AbstractMaestroExecutor.java#L56) which does the same but also retains the references to the topics.

**Comment by orpiske** [comment]
I pushed a PR that should fix this. If you still see the issue, just let me know and I'll investigate further. Thanks!

**Comment by k-wall** [comment]
Great thanks. I'll give the new images a try.

**Comment by orpiske** [comment]
The new images are out. They contain this fix + the recent fixes + improvements for the last 2 days.
