### ISSUE TITLE
JMSExceptions on the sender at the end of the test 

### ISSUE THREAD

**Issue by orpiske** [maestro-performance/maestro-java#96]
This happens only on QPid Dispatch which uses AMQP protocol. The code is using QPid JMS 0.27. 

> javax.jms.JMSException: Delivery failed: released by receiver
>         at org.apache.qpid.jms.provider.amqp.AmqpFixedProducer.processDeliveryUpdates(AmqpFixedProducer.java:247)
>         at org.apache.qpid.jms.provider.amqp.AmqpProvider.processUpdates(AmqpProvider.java:930)
>         at org.apache.qpid.jms.provider.amqp.AmqpProvider.access$1800(AmqpProvider.java:102)
>         at org.apache.qpid.jms.provider.amqp.AmqpProvider$17.run(AmqpProvider.java:792)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 

And:

> 
> javax.jms.JMSException: Delivery failed: released by receiver
>         at org.apache.qpid.jms.provider.amqp.AmqpFixedProducer.processDeliveryUpdates(AmqpFixedProducer.java:247)
>         at org.apache.qpid.jms.provider.amqp.AmqpProvider.processUpdates(AmqpProvider.java:930)
>         at org.apache.qpid.jms.provider.amqp.AmqpProvider.access$1800(AmqpProvider.java:102)
>         at org.apache.qpid.jms.provider.amqp.AmqpProvider$17.run(AmqpProvider.java:792)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by orpiske** [comment]
After discussing w/ the QPid Dispatch: This is based on a discussion I had with Qpid Dispatch Router developers and the guess is that: if the receiver disconnects before the sender, some messages from the sender will be inflight on the router, but since the receiver will be shutting down those messages may not be acknowledged. This causes their delivery status to be unknown on the router and the disposition of this messages is then sent back to the sender as MODIFIED/undeliberable. This may cause JMSExceptions to be thrown by the sender.

**Comment by orpiske** [comment]
Closing as fixed.
